# See PEP 518 for the spec of this file
# https://www.python.org/dev/peps/pep-0518/

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name =  "netbox-aci-plugin"
version = "0.0.1"
authors = [
    {name = "Martin Hauser", email = "git@pheus.dev"},
]
description = "NetBox plugin for Cisco ACI."
readme = "README.md"
license = {file = "LICENSE"}

classifiers=[
    'Development Status :: 1 - Planning',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    "Programming Language :: Python :: 3 :: Only",
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]

requires-python = ">=3.9.0"

[project.optional-dependencies]
test = [
    "black==24.4.2",
    "check-manifest==0.49",
    "flake8",
    "flake8-pyproject",
    "pre-commit==3.7.0",
    "pytest==8.2.0",
]

[project.urls]
Documentation = "https://github.com/pheus/netbox-aci-plugin/blob/main/README.md"
Source = "https://github.com/pheus/netbox-aci-plugin"
Tracker = "https://github.com/pheus/netbox-aci-plugin/issues"

[tool.black]
line-length = 120
target_version = ['py39', 'py310', 'py311', 'py312']

[tool.setuptools.package-data]
netbox_aci_plugin = ["templates/**"]
